name: Release Typst document
on:
  push:
    tags:
      - 'v*'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: cachix/install-nix-action@v30
      - run: nix run . -- compile erlang-binary-cheatsheet.typ
      - name: Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: erlang-binary-cheatsheet.pdf
